#!/bin/bash

set -x

wantedname=$1
wm=$2

echo "KEYMAP=fi" >> /mnt/etc/vconsole.conf

if (( $wm == 3)); then
arch-chroot /mnt pacman --noconfirm -S dialog wpa_supplicant xorg-server xorg-xinit xterm xf86-video-intel xf86-input-synaptics xmonad xmonad-contrib dmenu vim wget feh xorg-xdpyinfo xcompmgr transset-df xmobar firefox
echo $'if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then\n  startx\nfi' >> /mnt/home/$wantedname/.bash_profile
#echo $'setxkbmap fi &\nfeh --bg-scale ~/Downloads/archbackground.jpg &\nxcompmgr -c &\nxterm &\nexec xmonad' >> /mnt/home/$wantedname/.xinitrc
echo $'[ -n "$XTERM_VERSION" ] && transset-df --id "$WINDOWID" 0.45 >/dev/null' >> /mnt/home/$wantedname/.bashrc
mkdir -p /mnt/home/$wantedname/.xmonad
cp ./dotfiles/xmonad.hs /mnt/home/$wantedname/.xmonad/
cp ./dotfiles/.vimrc /mnt/home/$wantedname/
cp ./dotfiles/.xmobarrc /mnt/home/$wantedname/
else
arch-chroot /mnt pacman --noconfirm -S xorg-xinit xorg-server openbox obconf xterm cairo-dock cairo-dock-plug-ins firefox
echo $'if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then\n  startx\nfi' >> /mnt/home/$wantedname/.bash_profile
echo $'setxkbmap fi &\nexec openbox-session' >> /mnt/home/$wantedname/.xinitrc
echo $'cairo-dock -o &' >> /mnt/home/$wantedname/.config/openbox/autostart
fi

arch-chroot /mnt systemctl enable dhcpcd.service
cp ./dotfiles/.Xdefaults /mnt/home/$wantedname/
#cp ./dotfiles/.xinitrc /mnt/home/$wantedname/
cp ./dotfiles/70-synaptics.conf /mnt/etc/X11/xorg.conf.d/

cp ./archbackground.jpg /mnt/home/$wantedname/Downloads/
arch-chroot chown -R $wantedname /home/$wantedname/

set +x
