#!/bin/bash
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# Run this script after your first boot with archlinux (as root)
read -p 'Username: ' wantedname

read -p 'Give me installation device (ex. /dev/sda): ' diskpart
read -p 'Give me EFI partition (ex. /dev/sda1): ' efipart
read -p 'Give me Linux partition (ex. /dev/sda2): ' linuxpart

set -x
loadkeys fi
umount $linuxpart
mkfs.ext4 -F $linuxpart
umount $efipart
mkfs.fat -F32 $efipart
mount $linuxpart /mnt
mkdir -p /mnt/boot
mount $efipart /mnt/boot
pacstrap /mnt base
genfstab -U /mnt >> /mnt/etc/fstab
genfstab -U /mnt/boot >> /mnt/etc/fstab

arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
arch-chroot /mnt hwclock --systohc
#arch-chroot /mnt locale-gen
#echo $'KEYMAP="fi-winkeys"\nFONT="eurlatgr"' >> /mnt/etc/vconsole.conf
#setxkbmap fi
#echo "localhost.localdomain" >> /mnt/etc/hostname

arch-chroot /mnt pacman --noconfirm -S grub efibootmgr
arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub
#arch-chroot /mnt efibootmgr -c -d /dev/sda -p 1 -L "Archlol" -l "/boot/EFI/grub/grubx64.efi"
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg 



arch-chroot /mnt useradd -m -G wheel -s /bin/bash $wantedname
arch-chroot /mnt pacman --noconfirm -S sudo dialog wpa_supplicant
echo $wantedname" ALL=(ALL) ALL" >> /mnt/etc/sudoers
#echo "127.0.1.1	arch.localdomain	arch" >> /mnt/etc/hosts

arch-chroot /mnt pacman --noconfirm -S weston xorg-server-xwayland gnome
echo $'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]; then\nXDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session\nfi' >> /mnt/home/$wantedname/.bash_profile
#arch-chroot /mnt pacman --noconfirm -S weston plasma-meta plasma-wayland-session
#cp ./.vimrc /mnt/home/$wantedname/
echo "en_US" >> /mnt/home/$wantedname/.config/user-dirs.locale
mkdir -p /mnt/home/$wantedname/Pictures/
cp ./archbackground.jpg /mnt/home/$wantedname/Pictures/
arch-chroot chown -R $wantedname:users /home/$wantedname/

set +x
echo 'Give me root password:'
arch-chroot /mnt passwd
echo 'Give me user password:'
arch-chroot /mnt passwd $wantedname
