#!/bin/bash
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# Run this script after your first boot with archlinux (as root)
read -p 'Username: ' wantedname
read -p 'Using UEFI? (1, 0): ' uefi
if (( $uefi == 1))
then
read -p 'Give me EFI partition (ex. /dev/sda2): ' efipart
else
read -p 'Give me installation device (ex. /dev/sda): ' efipart
fi
read -p 'Give me Linux partition (ex. /dev/sda1): ' linuxpart

set -x
loadkeys fi
mkfs.ext4 $linuxpart
mount $linuxpart /mnt
pacstrap /mnt base
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
arch-chroot /mnt hwclock --systohc
arch-chroot /mnt echo "fi.utf8" >> /etc/locale.gen
arch-chroot /mnt locale-gen
arch-chroot /mnt echo "KEYMAP=fi" >> /etc/vconsole.conf
arch-chroot /mnt echo "arch" >> /etc/hostname
arch-chroot /mnt pacman --noconfirm -S grub
if (( $uefi == 1 )) 
then
  mkfs.fat -F32 $efipart
  mount $efipart /boot
  genfstab -U /boot >> /mnt/etc/fstab
  grub-install --target=x86_64-efi --efi-directory=/boot --root-directory=/mnt --bootloader-id=grub
else
  arch-chroot /mnt grub-install $efipart
fi
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
useradd -m -G wheel -s /bin/bash $wantedname
arch-chroot /mnt pacman --noconfirm -S dialog wpa_supplicant xorg-server xorg-xinit xmonad
set +x
echo 'Give me root password:'
passwd
echo 'Give me user password:'
passwd $wantedname
