#!/bin/bash

set -x

wantedname=$1
wm=$2

echo "KEYMAP=fi" >> /mnt/etc/vconsole.conf

if (( $wm == 3)); then
arch-chroot /mnt pacman --noconfirm -S dialog wpa_supplicant xorg-server xorg-xinit xterm xf86-video-intel xf86-input-synaptics xmonad xmonad-contrib dmenu vim wget feh xorg-xdpyinfo xcompmgr transset-df xmobar firefox
echo $'if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then\n  startx\nfi' >> /mnt/home/$wantedname/.bash_profile
#echo $'setxkbmap fi &\nfeh --bg-scale ~/Downloads/archbackground.jpg &\nxcompmgr -c &\nxterm &\nexec xmonad' >> /mnt/home/$wantedname/.xinitrc
echo $'[ -n "$XTERM_VERSION" ] && transset-df --id "$WINDOWID" 0.45 >/dev/null' >> /mnt/home/$wantedname/.bashrc
mkdir -p /mnt/home/$wantedname/.xmonad
cp ./dotfiles/xmonad.hs /mnt/home/$wantedname/.xmonad/
cp ./dotfiles/.vimrc /mnt/home/$wantedname/
cp ./dotfiles/.xmobarrc /mnt/home/$wantedname/
cp ./xmonad/.xinitrc /mnt/home/$wantedname/
cp ./dotfiles/.Xdefaults /mnt/home/$wantedname/
cp ./dotfiles/70-synaptics.conf /mnt/etc/X11/xorg.conf.d/
fi
if (( $wm == 4)); then
arch-chroot /mnt pacman --noconfirm -S xorg-xinit xorg-server wpa_supplicant dialog xf86-video-intel openbox obconf feh xterm chromium thunar xcompmgr cairo-dock cairo-dock-plug-ins
echo $'if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then\n  startx\nfi' >> /mnt/home/$wantedname/.bash_profile
echo $'setxkbmap fi &\nfeh --bg-scale ~/Pictures/archbackground.jpg &\nxcompmgr &\nexec openbox-session' >> /mnt/home/$wantedname/.xinitrc
mkdir -p /mnt/home/$wantedname/.config/openbox/
echo $'cairo-dock &' >> /mnt/home/$wantedname/.config/openbox/autostart
fi
if (( $wm == 5)); then
arch-chroot /mnt pacman --noconfirm -S xorg-xinit xorg-server dialog wpa_supplicant xf86-video-intel lxqt breeze-icons connman chromium git 
echo $'if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then\n  startx\nfi' >> /mnt/home/$wantedname/.bash_profile
echo $'setxkbmap fi &\nexec startlxqt' >> /mnt/home/$wantedname/.xinitrc
arch-chroot /mnt systemctl enable connman.service
cp ./lxqt/script /mnt/home/$wantedname/
fi

#arch-chroot /mnt systemctl enable dhcpcd.service

mkdir -p /mnt/home/$wantedname/Pictures
cp ./archbackground.jpg /mnt/home/$wantedname/Pictures/
arch-chroot /mnt chown -R $wantedname /home/$wantedname/

set +x
