#!/bin/bash
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# Run this script after your first boot with archlinux (as root)
read -p 'Username: ' wantedname
read -p 'Using UEFI? (1, 0): ' uefi
if (( $uefi == 1))
then
read -p 'Give me EFI partition (ex. /dev/sda1): ' efipart
else
read -p 'Give me installation device (ex. /dev/sda): ' efipart
fi
read -p 'Give me Linux partition (ex. /dev/sda2): ' linuxpart

set -x
loadkeys fi
umount $efipart
umount $linuxpart
mkfs.ext4 -F $linuxpart
mount $linuxpart /mnt
if (( $uefi == 1 )) 
then
  umount $efipart
  mkfs.fat -F32 $efipart
  mkdir /mnt/boot
  mount $efipart /mnt/boot
fi

pacstrap /mnt base
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
arch-chroot /mnt hwclock --systohc
arch-chroot /mnt locale-gen
echo "KEYMAP=fi" >> /mnt/etc/vconsole.conf
echo "arch" >> /mnt/etc/hostname

if (( $uefi == 1 )) 
then
#  genfstab -U /boot >> /mnt/etc/fstab
#  bootctl --path=/boot install
  mkdir -p /mnt/boot/loader
  echo $'default  arch\ntimeout  4\neditor   0' >> /mnt/boot/loader/loader.conf
  mkdir -p /mnt/boot/loader/entries
  echo $'title          Arch Linux\nlinux          /vmlinuz-linux\ninitrd         /initramfs-linux.img' >> /mnt/boot/loader/entries/arch.conf
else
  arch-chroot /mnt pacman --noconfirm -S grub
  arch-chroot /mnt grub-install $efipart
fi

arch-chroot /mnt useradd -m -G wheel -s /bin/bash $wantedname
arch-chroot /mnt pacman --noconfirm -S dialog wpa_supplicant sudo
echo $wantedname" ALL=(ALL) ALL" >> /mnt/etc/sudoers
echo "127.0.1.1	arch.localdomain	arch" >> /mnt/etc/hosts
arch-chroot /mnt systemctl enable dhcpcd.service
set +x
echo 'Give me root password:'
arch-chroot /mnt passwd
echo 'Give me user password:'
arch-chroot /mnt passwd $wantedname
