#!/bin/bash

wantedname=$1
wm=$2

## Install wayland, wayland x compability support, wifi compability additions and better ntfs support for external drives and usb sticks
arch-chroot /mnt pacman --noconfirm -S wayland xorg-server-xwayland ntfs-3g

## Install the desktop environment 
if (( $wm == 1)); then
arch-chroot /mnt pacman --noconfirm -S gnome gnome-tweak-tool gedit networkmanager dialog wpa_supplicant file-roller
arch-chroot /mnt pacman --noconfirm -Rns baobab epiphany gdm gnome-backgrounds gnome-calendar gnome-characters gnome-clocks gnome-contacts gnome-dictionary gnome-documents gnome-font-viewer gnome-getting-started-docs gnome-logs gnome-maps gnome-music gnome-photos gnome-todo gnome-user-docs gnome-user-share orca rygel sushi totem yelp gnome-boxes gnome-software simple-scan
#arch-chroot /mnt pacman --noconfirm -S gnome-tweak-tool dialog wpa_supplicant file-roller gedit gnome-calculator gnome-color-manager gnome-control-center gnome-disk-utility gnome-keyring gnome-menus gnome-screenshot gnome-session gnome-settings-daemon gnome-shell gnome-shell-extensions gnome-system-monitor gnome-terminal gnome-video-effects gvfs gvfs-afc gvfs-gphoto2 gvfs-mtp gvfs-smb mousetweaks mutter nautilus networkmanager 
arch-chroot /mnt systemctl enable NetworkManager.service
echo $'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]; then\nXDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session\nfi' >> /mnt/home/$wantedname/.bash_profile
elif (( $wm == 2)); then
arch-chroot /mnt pacman --noconfirm -S plasma-desktop plasma-wayland-session plasma-nm kate yakuake dolphin powerdevil ark gwenview kmix
arch-chroot /mnt systemctl enable NetworkManager.service
## Modify language here ~/.config/kxkbrc in future
echo $'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]; then\nXDG_SESSION_TYPE=wayland exec dbus-run-session startplasmacompositor\nfi' >> /mnt/home/$wantedname/.bash_profile
elif (( $wm == 3)); then
arch-chroot /mnt pacman --noconfirm -S enlightenment terminology connman
arch-chroot /mnt systemctl enable connman.service
echo $'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]; then\nenlightenment_start\nfi' >> /mnt/home/$wantedname/.bash_profile
else
arch-chroot /mnt pacman --noconfirm -S dialog wpa_supplicant sway rxvt-unicode dmenu
echo $'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]; then\nXKB_DEFAULT_LAYOUT=fi exec sway\nfi' >> /mnt/home/$wantedname/.bash_profile
arch-chroot /mnt cp /etc/sway/config /home/$wantedname/.config/sway/config
arch-chroot /mnt echo input $(swaymsg -t get_inputs | grep Synaptics | grep identifier | sed 's/.*identifier": //g' | sed 's/\,//g') $'{\n    tap enabled\n    natural_scroll enabled\n}' >> /home/$wantedname/.config/sway/config
arch-chroot /mnt echo -e $'bindsym XF86AudioRaiseVolume exec pactl set-sink-volume $(pacmd list-sinks |awk '/* index:/{print $3}') +5%\nbindsym XF86AudioLowerVolume exec pactl set-sink-volume $(pacmd list-sinks |awk '/* index:/{print $3}') -5%\nbindsym XF86AudioMute exec pactl set-sink-mute $(pacmd list-sinks |awk '/* index:/{print $3}') toggle\nbindsym XF86MonBrightnessDown exec brightnessctl set 5%-\nbindsym XF86MonBrightnessUp exec brightnessctl set +5%' >> /home/$wantedname/.config/sway/config
fi

## Install some favourite tools
#arch-chroot /mnt pacman --noconfirm -S virtualbox-guest-utils
arch-chroot /mnt pacman --noconfirm -S firefox git
#arch-chroot /mnt pacman --noconfirm -S flashplugin npm qbittorrent minidlna libreoffice-still calibre adobe-source-code-pro-fonts vulkan-intel xf86-video-intel
#arch-chroot /mnt systemctl enable minidlna.service
##arch-chroot /mnt pacman --noconfirm -S unrar gst-plugins-good vlc phonon-qt4-vlc mpd cantata fuseiso perl-image-exiftool pgadmin4

