#!/bin/bash
echo "Round 1"
#curl https://www.sa-cd.net/dsd | grep "color:black;text-decoration:none" | sed 's/.*none">//g' | sed 's/<\/a>.*//g' >> file1
curl https://www.sa-cd.net/dsd | grep "color:black;text-decoration:none" | sed 's/.*showtitle\///g' | sed 's/\".*//g' >> file1
for i in {2..75}
do
	echo "Round $i"
	#curl https://www.sa-cd.net/dsd/$i | grep "color:black;text-decoration:none" | sed 's/.*none">//g' | sed 's/<\/a>.*//g' >> file1
	curl https://www.sa-cd.net/dsd/$i | grep "color:black;text-decoration:none" | sed 's/.*showtitle\///g' | sed 's/\".*//g' >> file1
done
