#!/bin/bash
# Run this script with command 'gnome-terminal -- sudo ~/update'
curl -o /etc/pacman.d/mirrorlist 'https://www.archlinux.org/mirrorlist/?country=AT&country=BY&country=BE&country=BA&country=BG&country=HR&country=CZ&country=DK&country=FI&country=FR&country=DE&country=GR&country=HU&country=IS&country=IE&country=IL&country=IT&country=LV&country=LT&country=LU&country=NL&country=NO&country=PL&country=PT&country=RO&country=RS&country=SK&country=SI&country=ES&country=SE&country=CH&country=UA&country=GB&protocol=http&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on'
sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist
powerpill -Syu
sudo -u username yay -Syu
